### PR TITLE
update redis and testify to new version

### LINKED ISSUE #37: Missing ScanType Method
Using github.com/go-redis/redis/v8 v8.4.4, I get the following error

```
Cannot use 'mock' (type *redismock.ClientMock) as type redis.Cmdable Type does not implement 'redis.Cmdable' as some methods are missing: ScanType(ctx context.Context, cursor uint64, match string, count int64, keyType string) *ScanCmd
```

### PR DESCRIPTION
**Pull request by lilien1010**
fix https://github.com/elliotchance/redismock/issues/37
and  support redis ScanType
Accomplish it in a better way like owner mentioned [here](https://github.com/elliotchance/redismock/issues/37#issuecomment-768388451)

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/redismock/38)

### CODE REVIEW

**Comment by lilien1010** [comment]
once this is merged  , need new tag for this commit

**Comment by lilien1010** [comment]
@elliotchance  need your review here

**Review by elliotchance — APPROVED** [review]

**Comment by lilien1010** [comment]
@elliotchance 
also can you  create a new tag version base on this PR when you have time?.
 our project is reply on this awesome project and it blocked our CI

**Comment by elliotchance** [comment]
@lilien1010 - https://github.com/elliotchance/redismock/releases/tag/v8.6.1

**Comment by lilien1010** [comment]
@elliotchance  thanks a lot

**Pull request merged**
